
version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - INFLUXDB_URL=http://db:8086


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend


  db:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2


  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"

volumes:
  influxdb-data: